name: dotnet build

on:
  push:
    branches: [ main, live ]
  pull_request:
    branches: [ main, live ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
    - name: Setup .NET
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
      with:
        dotnet-version: 10.x
    - name: Restore dependencies
      working-directory: user-auth/GraphTutorial/
      run: dotnet restore
    - name: Build
      working-directory: user-auth/GraphTutorial/
      run: dotnet build --no-restore
    - name: Restore dependencies
      working-directory: app-auth/GraphAppOnlyTutorial/
      run: dotnet restore
    - name: Build
      working-directory: app-auth/GraphAppOnlyTutorial/
      run: dotnet build --no-restore
